import type { TaskDef } from "./types.js";

export const TASK_CATALOG: TaskDef[] = [
  {
    id: "code-review",
    kind: "code",
    useCases: ["code"],
    titleKey: "taskCodeReviewTitle",
    promptKey: "taskCodeReviewPrompt",
    harnessId: "H-CODE-REVIEW",
  },
  {
    id: "code-tests",
    kind: "code",
    useCases: ["code"],
    titleKey: "taskCodeTestsTitle",
    promptKey: "taskCodeTestsPrompt",
    harnessId: "H-CODE-TESTS",
  },
  {
    id: "chat-plan",
    kind: "chat",
    useCases: ["chat"],
    titleKey: "taskChatPlanTitle",
    promptKey: "taskChatPlanPrompt",
    harnessId: "H-CHAT-PLAN",
  },
  {
    id: "chat-agent",
    kind: "chat",
    useCases: ["chat", "code"],
    titleKey: "taskChatAgentTitle",
    promptKey: "taskChatAgentPrompt",
    harnessId: "H-CHAT-AGENT",
  },
  {
    id: "image-caption",
    kind: "image",
    useCases: ["image", "vision"],
    titleKey: "taskImageCaptionTitle",
    promptKey: "taskImageCaptionPrompt",
    harnessId: "H-IMAGE-CAPTION",
  },
  {
    id: "image-edit-brief",
    kind: "image",
    useCases: ["image", "vision"],
    titleKey: "taskImageBriefTitle",
    promptKey: "taskImageBriefPrompt",
    harnessId: "H-IMAGE-BRIEF",
  },
  {
    id: "video-storyboard",
    kind: "video",
    useCases: ["video"],
    titleKey: "taskVideoBoardTitle",
    promptKey: "taskVideoBoardPrompt",
    harnessId: "H-VIDEO-BOARD",
  },
  {
    id: "video-shotlist",
    kind: "video",
    useCases: ["video"],
    titleKey: "taskVideoShotTitle",
    promptKey: "taskVideoShotPrompt",
    harnessId: "H-VIDEO-SHOTS",
  },
  {
    id: "transcribe-clean",
    kind: "transcription",
    useCases: ["chat", "multilingual"],
    titleKey: "taskTranscribeCleanTitle",
    promptKey: "taskTranscribeCleanPrompt",
    harnessId: "H-ASR-CLEAN",
  },
  {
    id: "transcribe-actions",
    kind: "transcription",
    useCases: ["chat", "code"],
    titleKey: "taskTranscribeActionsTitle",
    promptKey: "taskTranscribeActionsPrompt",
    harnessId: "H-ASR-ACTIONS",
  },
];
